TeamSynergym/frontend-web

- src/App.tsx
- src/components/common/Header.tsx
- src/pages/Login.tsx
> feat(login_ui): complete login screen UI design and layout

- src/api/authApi.ts
- src/api/axiosInstance.ts
- src/pages/Login.tsx
> feat(login_axios): complete login feature using Axios for Login module

- package-lock.json
- package.json
- pnpm-lock.yaml
- src/api/authApi.ts
- src/components/ui/select.tsx
- src/pages/Login.tsx
- src/pages/Signup.tsx
- src/types/auth.ts
- 이메일 인증 코드 발송 및 검증 기능 구현 (redis, docker 사용)
- 회원가입 시 이메일 인증 필수 적용
- 로그인 및 회원가입 API 로직 최종 마무리
- JWT 토큰 발급 및 비밀번호 암호화 처리 포함
- 관련 DTO, Service, Controller 구현 완료
> feat: complete email verification and auth (signup & login)

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/api/authApi.ts
- src/components/ui/tabs.tsx
- src/pages/FindCredentials.tsx
- src/pages/Login.tsx
- src/types/auth.ts
- 사용자 아이디 찾기 추가 (이메일, 생년월일 등으로 조회)
- 비밀번호 재설정 추가
> feat: add find ID & password functionality

- package.json
- pnpm-lock.yaml
- src/components/signup/ConfirmPasswordField.tsx
- src/components/signup/GoalField.tsx
- src/components/signup/NameField.tsx
- src/components/signup/PasswordField.tsx
- src/components/signup/ProfileImageUpload.tsx
- src/components/signup/SensitiveInfoToggle.tsx
- src/components/ui/switch.tsx
- src/pages/Signup2.tsx
- src/types/events.d.ts
> wip(join): start working on Signup component UI for Join module

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/api/authApi.ts
- src/pages/Login.tsx
- src/pages/OAuth2RedirectHandler.tsx
- src/pages/Signup.tsx
- src/pages/SocialSignupPage.tsx
- src/types/auth.ts
- 소셜 로그인 버튼 추가
- 백엔드 소셜 로그인 API와 연동
- 로그인 성공 시 JWT 토큰 발급
> feat: add social login UI and integrate with backend API

- src/pages/Login.tsx
- src/store/userStore.ts
- add userStore
- edit login.tsx
> feat(store) : add userStore

- src/pages/Login.tsx
- src/store/userStore.ts
- src/types/auth.ts
- Replace int id approach with User for complete user info
- Store essential user fields (id, email, name, role) in localStorage
> feat(store) : edit  user authentication with Zustand store

- src/App.tsx
- src/pages/Login.tsx
- src/pages/PhotoUpload.tsx
- src/pages/PhotoUploadLoading.tsx
- Add PhotoUploadLoading page with loading and completion states
- Integrate userStore for authentication check in PhotoUpload and PhotoUploadLoading
- Implement redirect to original page after login using location state
> feat(upload): Add photo upload loading page with user authentication

- package-lock.json
- src/App.tsx
- src/components/common/Header.tsx
- src/pages/CommunityDetailPage.tsx
- src/pages/CommunityPage.tsx
- src/pages/CommunityWritePage.tsx
- src/services/api/communityApi.ts
- src/types/community.ts
- Implement all community features: main/list, detail, create/edit, comments, likes, etc.
> feat(community) : Implement frontend features and resolve major issues

- src/components/dashboard/TodayRoutineCard.tsx
- src/components/exercise/ExerciseCard.tsx
- src/components/exercise/ExerciseFilter.tsx
- src/components/log/DailyLogComponent.tsx
- src/components/log/ExerciseCalendar.tsx
- src/components/mypage/LikedExerciseSection.tsx
- src/pages/Dashboard.tsx
- src/pages/log.tsx
- src/services/api/exerciseLogApi.ts
- src/store/dashboardStore.ts
- src/store/logStore.ts
- 운동기록시작 버튼 클릭 시 기록 페이지로 이동 기능 추가
- 운동 기록에 메모 입력 기능 추가
- 운동기록시작 섹션에서 오늘 할 루틴 선택 기능 구현
- 운동목록 페이지 디자인 개선
- 좋아요한 운동 클릭 시 운동 상세 페이지로 이동 및 이미지 비율 문제 수정
> feat: add exercise-log memo, improve ui

- src/components/community/CommunityFilters.tsx
- src/components/community/PostActions.tsx
- src/components/community/PostCard.tsx
- src/components/community/PostCounter.tsx
- src/components/community/PostHeader.tsx
- src/components/community/index.ts
- src/pages/CommunityDetailPage.tsx
- src/pages/CommunityPage.tsx
- src/pages/CommunityWritePage.tsx
- src/services/api/communityApi.ts
- src/types/community.ts
- Split components into reusable modules (PostCounter, PostCard, etc.)
- Create custom hooks for state management (usePostsList, useLikeStates, etc.)
- Improve code organization and maintainability
- Add proper TypeScript types and error handling
- Enhance mobile responsiveness and accessibility
> feat(community) : refactor community components and improve code organization

- src/pages/CommunityDetailPage.tsx
- Replace client-side view count management with server-based approach
- Add fetchPostViewCount API integration for real-time view count updates
- Implement incrementViewCount and refreshViewCount functions
- Remove session storage based view count logic
- Add server-side view count fetching after post load
- Improve data consistency between client and server
- Add debugging functions for view count management
- Fix userId parameter passing in like and comment operations
Resolves: View count accuracy and client-server synchronization issues
> feat(community): Implement server-based view count management

- src/components/dashboard/CommunityHotPosts.tsx
- src/pages/Dashboard.tsx
- Add click-to-navigate functionality for community hot post cards
- Include post IDs in hot posts data structure
- Navigate to /community/{postId} when clicking on post cards
> feat: Add click navigation to community hot posts in dashboard

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/components/common/AdminHeader.tsx
- src/components/common/AdminLayout.tsx
- src/components/common/Pagination.tsx
- src/components/common/StatCard.tsx
- src/components/ui/dropdown-menu.tsx
- src/components/ui/sheet.tsx
- src/components/ui/skeleton.tsx
- src/components/ui/table.tsx
- src/pages/AdminDashboard.tsx
- src/pages/CommunityManagementPage.tsx
- src/pages/Login.tsx
- src/pages/MemberManagementPage.tsx
구현:
- 반응형 사이드바 탐색 기능
- 사용자 분석결과 통계 확인 대시보드 구현
- 검색 및 삭제 기능이 있는 회원 관리 페이지
- 게시물 및 카테고리에 대한 콘텐츠 관리 추가
관리자 기능:
- 대시보드: 회원 통계, 성별 분석, 연령대 분석, 인기 있는 운동
- 회원 관리: 검색, 강제 계정 삭제
- 콘텐츠 관리: 카테고리 CRUD, 게시물 삭제
> feat: admin management system implementation

- src/App.tsx
- src/components/chat/ChatModal.tsx
- src/pages/AnalysisResultPage.tsx
- src/pages/AnalysisSharePage.tsx
- Add share button to AnalysisResultPage with responsive design
- Create read-only AnalysisSharePage for shared results
- Implement direct URL sharing without modal dialog
- Add /analysis-share/:historyId route
- Hide chatbot on shared pages for better UX
- Add fallback mock data
- Include signup CTA for non-members on shared pages
> feat : Implement analysis result sharing functionality

- src/components/common/Header.tsx
- Redirect unauthenticated users to login page when accessing /community or /exercises
> feat(header): add authentication check for community and exercises pages

- src/pages/AdminDashboard.tsx
- src/pages/CommunityDetailPage.tsx
- Display top posts by likes, comments, and views
- Enable click-to-navigate functionality for each post
- Add pagination and hover effects for better UX
- Include proper error handling and logging
> feat : Add popular posts statistics with navigation to admin dashboard

- src/App.tsx
- src/components/chat/ChatModal.tsx
- src/components/common/AdminLayout.tsx
- src/components/common/StatCard.tsx
- src/components/ui/grouped-bar-chart.tsx
- src/pages/AdminDashboard.tsx
- src/pages/CommunityManagementPage.tsx
- src/pages/MemberManagementPage.tsx
- src/pages/MemberStatsPage.tsx
- src/services/api/communityApi.ts
- Add real-time member statistics with signup growth, gender/age distribution charts
- Implement dark mode toggle in admin sidebar with consistent theming
- Optimize mobile responsiveness for member management and statistics pages
- Integrate backend API for user signup stats and admin dashboard data
- Remove dummy data and fix post list rendering in content management
- Enhance chart styling with consistent blue theme and proper mobile scaling
> feat: Implement admin dashboard with member statistics and dark mode

- src/api/axiosInstance.ts
- src/components/chat/ChatModal.tsx
- src/components/chat/TopButton.tsx
- src/components/common/AdminHeader.tsx
- src/components/common/AdminLayout.tsx
- src/components/common/Header.tsx
- src/components/common/MobileMenuModal.tsx
- src/components/common/Pagination.tsx
- src/components/common/StatCard.tsx
- src/components/community/CommunityFilters.tsx
- src/components/community/PostActions.tsx
- src/components/community/PostCard.tsx
- src/components/community/PostCounter.tsx
- src/components/community/PostHeader.tsx
- src/components/community/index.ts
- src/hooks/useRequireAuth.ts
- src/pages/CommunityPage.tsx
- src/pages/ExerciseListPage.tsx
- src/pages/PhotoUpload.tsx
- Refactored authentication logic: introduced a reusable hook to handle unauthenticated user redirects, ensuring consistent behavior across protected pages.
- Removed redundant authentication checks from individual components/pages and applied the common hook where needed.
> feat : unify redirect logic with a common hook and add comments

- src/components/chat/ChatModal.tsx
- src/components/common/AdminLayout.tsx
- src/components/common/Header.tsx
- src/components/home/Section1.tsx
- src/components/mypage/ExerciseRecordsSection.tsx
- src/pages/FindCredentials.tsx
- src/pages/Login.tsx
- src/pages/Signup.tsx
- src/pages/SocialSignupPage.tsx
- src/store/logStore.ts
- "SynergyM"에서 "Synergym"으로 로고 수정
- 로그인 페이지와 로그인 페이지
- 구글, 네이버, 카카오 아이콘과 소셜 로그인 버튼 수정
- 배경 및 텍스트 색깔 수정
- 운동 기록 통계에 대한 사용자별 필터링을 포함하도록 ExerciseRecordsSection 로직 리팩터링 (세션 루틴에 userId를 포함하도록 logStore 업데이트)
> UI enhancement

- src/pages/Login.tsx
- src/pages/Signup.tsx
> chore(change_ip): change request address from localhost to server IP

- src/pages/Login.tsx
- src/pages/Signup.tsx
> Add [http://] for social login

- src/components/chat/ChatModal.tsx
- src/components/chat/Chatbot.tsx
- src/pages/AnalysisResultPage.tsx
- src/pages/AnalysisSharePage.tsx
- src/services/api/chatbotApi.ts
- 챗봇 API 사용 방식 통합: 기존 callAiChatbotApi 제거, sendChatMessage, getChatHistory, getChatHistoryBySession만 사용하도록 전체 컴포넌트/페이지 리팩토링
- ChatModal 등 챗봇 관련 컴포넌트 일괄 수정 및 FastAPI 연동 구조로 통일
- 특정 세션별 대화내역 조회 기능 추가
- 모든 챗봇 메시지 전송/조회가 Spring → FastAPI로 바로 연동되도록 개선
- AnalysisSharePage의 UI/레이아웃을 AnalysisResultPage와 완전히 일치시킴(카드, 컬럼, 디자인, 구조 등)
- 사용하지 않는 DTO, 타입, import 등 정리
- 전체 평균 점수 계산 시 0점 제외하도록 로직 수정
- 공유용 페이지 통일
> Refactor chatbot integration and unify analysis result UI

- src/App.tsx
- src/components/mypage/BadgeCollectionSection.tsx
- src/pages/Dashboard.tsx
- src/pages/GoalRecommendationPage.tsx
- src/services/api/aiApi.ts
- src/services/api/notificationApi.ts
- src/services/api/userApi.ts
✅ 주요 변경 사항
- 대시보드에서 AI 목표 추천 기능 연결
- GoalRecommendationPage.tsx : 사용자 맞춤 목표 생성 페이지 추가
- 목표 추천 결과 및 분석 리포트 출력
- 동기 부여 뱃지 렌더링 완료
- AI 추천 시 생성된 뱃지를 화면에 출력하여 동기 부여 강화
📂 신규 파일
- GoalRecommendationPage.tsx : 목표 추천 UI 페이지
- aiApi.ts : AI 서버 연동 API
- userApi.ts : 사용자 관련 API 추가
> feat: Getting Goal Recommendations from Dashboard and Badge Rendering

- src/components/chat/ChatModal.tsx
- src/pages/AnalysisResultPage.tsx
- src/services/api/chatbotApi.ts
운동 추천 → 비디오 검색 → 스크립트 요약 → 댓글 요약 전체 워크플로우 구현
비디오 iframe 렌더링 및 댓글 요약 버튼 추가
snake_case/camelCase 필드 호환성 처리
상세한 디버그 로깅 및 에러 핸들링 개선
> feat: Implement complete AI chatbot workflow with video recommendations and comment summaries

- src/components/chat/ChatModal.tsx
- src/pages/AnalysisResultPage.tsx
- src/pages/PhotoUpload.tsx
- src/services/api/analysisApi.ts
- src/services/api/chatbotApi.ts
- ChatModal에서 type 필드 명확히 세팅하여 Spring 분기 오류 방지
- 분석/챗봇 요청 시 historyId, diagnosis 등 필요한 정보 포함하여 전달
- 사진 2장 업로드 시에도 그래프/점수/소견 정상 표시되도록 연동 개선
- 유튜브/AI코치 버튼 클릭 시 데이터 구조 일관성 유지
> feat: Refactor chatbot API integration and improve analysis request flow

- src/api/axiosInstance.ts
- src/pages/Login.tsx
- src/pages/PhotoUpload.tsx
> refactor(url): dynamically set host URL based on request origin

- package.json
- pnpm-lock.yaml
- src/components/chat/ChatModal.tsx
- src/pages/AnalysisResultPage.tsx
- src/types/index.ts
- AI 코치 챗봇 초기 메시지 생성 로직 개선 및 답변 UX 향상
- react-markdown, remark-gfm 적용으로 AI 답변에 마크다운/줄바꿈 지원
- 답변 생성 중 로딩 스피너 및 안내 메시지 표시
- ChatModal이 열릴 때마다 Redis에서 대화내역을 불러와 messages 상태에 누적 저장
- AI 답변 생성 시 이전 대화내역이 사라지지 않도록 setMessages(prev => [...prev, userMsg, botMsg])로 수정
- 메뉴 이동/새로고침 후에도 유저 메시지와 AI 답변이 정상적으로 복원되도록 구조 개선
- 챗봇이 열릴 때마다 최신 메시지로 자동 스크롤
> Feat: Improve AI coach chat UX, markdown support, and persistent chat history

- src/components/dashboard/TodayRoutineCard.tsx
- src/components/log/DailyLogComponent.tsx
- src/pages/Dashboard.tsx
fix: fixed bug in workout record saving logic
> fix: fixed bug in workout record saving logic

- src/services/api/emotionLogApi.ts
- src/store/emotionLogStore.ts
- src/store/logStore.ts
- 로그찍히는거 리를빗 수정
- 메모 비어있고 운동기록만 저장할때의 로직 추가
- 같은 날짜에 여러개의 기록이 있는경우 하나만 가져오도록
- 메모 업데이트 - 감정 업데이트 연결 확인
> feat: add emotion log rendering

- src/api/axiosInstance.ts
- vite.config.ts
> feat(nginx_setting): configure reverse proxy for Vite dev server

- src/components/chat/ChatModal.tsx
- src/components/home/Section3.tsx
- src/pages/AnalysisResultPage.tsx
- 홈페이지 서비스 사진 변경
- 필요없는 console 코드 삭제
> ui & refactor : change wall paper and delete console code

- src/components/chat/ChatModal.tsx
- src/components/chat/Chatbot.tsx
- src/components/exercise/AddToRoutineModal.tsx
- src/components/exercise/ExerciseCard.tsx
- src/components/exercise/ExerciseFilter.tsx
- src/components/exercise/RecommendedExercises.tsx
- src/components/exercise/RecommendedExercisesLoader.tsx
- src/components/mypage/AnalysisHistorySection.tsx
- src/pages/AnalysisResultPage.tsx
- src/pages/ExerciseDetailPage.tsx
- src/pages/ExerciseListPage.tsx
- src/pages/GoalRecommendationPage.tsx
- src/services/api/analysisApi.ts
- src/services/api/chatbotApi.ts
- 유투브 영상 챗봇에 띄우기
*유투브 스크립트, 댓글분석은 ip 차단되어서 확인 못함
- ai 코치 대화나 유투브 영상 둘다 이전 대화목록 잘 불러오도록 설정
- 신규루틴 추가, 기존루틴 추가 완료
- 챗봇 UI, 다크모드
- 운동목록 페이지네이션
> feat(chatbot, ui): support YouTube video display, persistent chat history, dark mode, and exercise list pagination
